clinica/app_pacientes/urls.py
from django.urls import path, include
from . import views

app_name = "app_pacientes"

urlpatterns = [
    path('agregar', views.agregar, name="agregar"),
    path('', views.index, name="index"),
    path('/h', views.home, name="home"),
]

clinica/app_pedidos/urls.py
from django.urls import path, include
from . import views

app_name = "app_pedidos"

urlpatterns = [
    path('', views.index, name="index"),
    path('/pedido', views.imprimir, name="index"),
    path('/nuevo', views.nuevo, name="nuevo"),
]

clinica/app_turnos/urls.py
from django.urls import path, include
from . import views

app_name ="app_turnos"

urlpatterns = [
    path('', views.index, name="index"),
]

clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from clinica_APP.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinica/', include("clinica_APP.urls")),
    path('clinica/turno', include("app_turnos.urls")),
    path('clinica/pedido', include("app_pedidos.urls")),
    path('clinica/paciente', include("app_pacientes.urls")),
]

clinica/clinica_APP/urls.py
from django.urls import path, include
from . import views

app_name = "clinica_APP"

urlpatterns = [
    path('', views.index, name="index"),
    # path("agregar", views.agregar, name=“agregar")
    path('secretaria', views.secretaria, name="secretaria"),
]

clinica/app_pacientes/models.py
from django.db import models
from app_turnos import *

# Create your models here.


class Paciente(models.Model):
    nombrePac = models.CharField(max_length=64)
    apellidoPac = models.CharField(max_length=64)
    dniPac = models.IntegerField()
    telefonoP = models.IntegerField()
    fecha_nacPac = models.DateField()


class HistorialMedico:
   paciente_id = models.ForeignKey(
       Paciente, on_delete=models.CASCADE, related_name="paciente")

clinica/app_pedidos/models.py
from django.db import models

# Create your models here.

clinica/app_turnos/models.py
from django.db import models
# import paquete.modulo1
# import app_pacientes.models
from app_pacientes.models import Paciente
# Create your models here.


class Medico(models.Model):
    nombreMed = models.CharField(max_length=64)
    apellidoMed = models.CharField(max_length=64)
    dniMed = models.IntegerField()
    telefonoMed = models.IntegerField()
    

class Turno(models.Model):
    fecha_turno = models.DateField()
    paciente_T = models.ForeignKey(Paciente, on_delete=models.CASCADE, related_name="paciente")
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE, related_name="paciente")

clinica/clinica_APP/models.py
from django.db import models

# Create your models here.

clinica/app_pacientes/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
import datetime

# Create your views here.


def index(request):
    return render(request, "secretaria/verPaciente.html")


# antiguo view
def agregar(request):
    return render(request, "secretaria/agregarPaciente.html", {
        "form": Form_datospersonales()
    }
    )


'''
def agregar(request):
    if request.method == "POST":
        form = Form_datospersonales(request.POST)
    if form.is_valid():
        datos = form.cleaned_data["app_paciente"]
        "app_pacientes": request.session["app_pacientes"]

# Agregar la nueva tarea a nuestra lista de tareas tareas.append(tarea)
# Redireccionar al usuario a la lista de tareas return HttpResponseRedirect(reverse("tareas:index"))
    else:  # Si el formulario es invalido, volver a renderizar la pagina con la informacion existente.
        return render(request, "app_pacientes/agregar.html", {
            "form": form
        })

    return render(request, "app_pacientes/agregar.html", {
        "form": Form_datospersonales()
    })
'''


def home(request):
    return render(request, "home.html")


class Form_datospersonales(forms.Form):
    nombre = forms.CharField(label="Nombre")
    apellido = forms.CharField(label="Apellido")
    dni = forms.IntegerField(label="DNI")
    telefono = forms.IntegerField(label="Telefono")
    fecha_nac = forms.DateField(initial=datetime.date.today)

clinica/app_pedidos/views.py
from django.shortcuts import render
from django import forms
# Create your views here.


def index(request):
    return render(request, "ventas/verProducto.html")


pedidos = ["pedido1", "pedido 2"]


def imprimir(request):
    return render(request, "ventas/verProducto.html", {
        "pedidos": pedidos
    })


class MiNuevoFormulario(forms.Form):
    producto = forms.CharField(label="Nuevo Producto")


# Agregando en el contexto del paso al template:


def nuevo(request):
    return render(request, "producto/nuevo.html", {
        "formulario_producto_nuevo": MiNuevoFormulario()
    })

clinica/app_turnos/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"secretaria/verTurno.html")

clinica/clinica_APP/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login
# Create your views here.


def index(request):
    return render(request, "index.html")



# def agregar(request):
   # return render(request, "tareas/agregar.html")


def ingresar(request):
    if (request.method == 'POST'):
        username = request.POST.get('menuRol')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect(pagina())

    return render(request, 'index.html',
                  {})


def pagina():
    # if(user==)
    #'nombre del name de url'
    # podria ser app:
    print("usuario ")


def secretaria(request):
    return render(request, "secretaria.html")

clinica/app_pacientes/templates/app_pacientes/agregarPaciente.html
<title>Agregar Paciente</title>

{% extends "home.html" %} {% block body %}
<!-- Button trigger modal -->
<div class="row justify-content-center">
    <form id="formulario" class="" action="{% url 'app_pacientes:index' %}" method="post">
        {% csrf_token %}
        <div class="container-fluid ">
            <label for="nombre">Nombre:</label>
            <input type="text" class="form-control" name="nombre" placeholder="ingrese nombre" minlength="5" maxlength="50" required />
        </div>
        <div class="container-fluid ">
            <label for="apellido">Apellido:</label>
            <input type="text" class="form-control" name="apellido" placeholder="ingrese apellido" minlength="5" maxlength="50" required />
        </div>
        <div class="container-fluid ">
            <label for="dni">DNI:</label>
            <input type="text" class="form-control" id="inputDNI" name="dni" placeholder="ingrese DNI" minlength="8" maxlength="9" required />
        </div>
        <div class="container-fluid ">
            <label for="telefono"> Telefono:</label>
            <input type="text" class="form-control" id="inputTelefono" class="form-control" id="inputTelefono" name="tel" placeholder="ingrese telefono ej. 45523344" minlength="8" maxlength="11" />
        </div>
        <div class="container-fluid ">
            <label for="fecha_nac">fecha de nacimiento :</label>
            <input type="date" id="fecha" class="form-control" name="fecha_nac" min="1900-01-01" required />
        </div>
        <button type="submit" class="btn btn-primary">
      Guardar
    </button>
    </form>

</div>



<!--
  form action="{% url 'app_pacientes:agregar' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit">
</form> -->

{% endblock %}

clinica/app_pacientes/templates/secretaria/agregarPaciente.html
<title>Agregar Paciente</title>

{% extends "home.html" %} {% block body %}
<!-- Button trigger modal -->

<form id="formulario" class="" action="{% url 'app_pacientes:index' %}" method="post">
    {% csrf_token %}

    <div class="container w-25">

        <div class="form-row">

            <div class="form-group col-md-6">
                <label for="inputNombre">Nombre</label>
                <input type="text" class="form-control" id="inputNombre" minlength="3" maxlength="40" placeholder="Nombre" required>
            </div>

            <div class="form-group col-md-6">
                <label for="inputApellido">Apellido</label>
                <input type="text" class="form-control" id="inputApellido" minlength="3" maxlength="40" placeholder="Apellido" required>
            </div>

        </div>

        <div class="form-group">
            <label for="inputDNI">DNI</label>
            <div class="input-group mb-2">
                <input type="text" class="form-control" id="inputDNI" minlength="8" maxlength="9" placeholder="Ejemplo: 11.222.333 (sin los puntos)" required>
            </div>
        </div>

        <div class="form-group">
            <label for="inputTelefono">Teléfono</label>
            <input type="text" class="form-control" id="inputTelefono" minlength="8" maxlength="12" placeholder="+54 11 55223344" required>
        </div>

        <div class="form-group">
            <label class="my-1 mr-2" for="inputFecha">Fecha</label>
            <input type="date" name="fecha" min="1900-01-01" class="form-control my-1 mr-sm-2" id="inputFecha" required>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>

    </div>

</form>


<!--
  form action="{% url 'app_pacientes:agregar' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit">
</form> -->

{% endblock %}

clinica/app_pacientes/templates/secretaria/verPaciente.html
<title>Home Paciente</title>

{% extends "home.html" %} {% block body %}
<!-- <a href="pacienteagregar">Agregar un nuevo paciente </a>
<a href="{% url 'app_pacientes:home' %}">home</a> -->
<style>
    * {
        margin: 0;
        padding: 0;
    }
    
    header {
        font-family: Helvetica;
        width: 480px;
        margin: 0 auto;
    }
    
    ul {
        list-style: none;
    }
    
    #menu li>a {
        background-color: grey;
        color: white;
        padding: 10px;
        display: block;
        text-decoration: none;
        min-width: 100px;
    }
    
    #menu li>a:hover {
        color: #000;
        background-color: #eaeaea;
    }
    
    #menu>li {
        float: left;
        text-align: center
    }
    
    #menu>li>ul {
        display: none;
    }
    
    #menu>li:hover>ul {
        display: block;
    }
</style>
<nav>
    <ul id="menu">
        <li><a href="../clinica">Inicio</a></li>
        <li><a href="../clinica/turno">Turno</a></li>
        <li><a href="../clinica/pedido">Pedido</a></li>
        <li><a href="../clinica/paciente">Paciente</a></li>
    </ul>
</nav>


<a href="{% url 'app_pacientes:agregar' %}">Agregar un nuevo paciente </a>

<input type="search" name="" id="buscador" />
<button value="buscar">
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    class="bi bi-search"
    fill="currentColor"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      fill-rule="evenodd"
      d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"
    />
    <path
      fill-rule="evenodd"
      d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"
    />
  </svg>
  Buscar
</button>

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">DNI</th>
            <th scope="col">Teléfono</th>
            <th scope="col">Fecha de Nacimiento</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td></td>
            <td></td>
            <td></td>
            <td> </td>
            <td> </td>

        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
            <td> </td>
            <td> </td>

        </tr>
        <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>@twitter</td>
            <td> </td>
            <td> </td>

        </tr>
    </tbody>
</table>
{% endblock %}
<!---</body>
</html> -->

clinica/app_pedidos/templates/ventas/nuevoProducto.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pedido</title>
  </head>
  <body>
{{ formulario_producto_nuevo }}

 </body>
</html>

clinica/app_pedidos/templates/ventas/verProducto.html
{% extends "home.html" %} {% block body %}
<style>
    * {
        margin: 0;
        padding: 0;
    }
    
    header {
        font-family: Helvetica;
        width: 480px;
        margin: 0 auto;
    }
    
    ul {
        list-style: none;
    }
    
    #menu li>a {
        background-color: grey;
        color: white;
        padding: 10px;
        display: block;
        text-decoration: none;
        min-width: 100px;
    }
    
    #menu li>a:hover {
        color: #000;
        background-color: #eaeaea;
    }
    
    #menu>li {
        float: left;
        text-align: center
    }
    
    #menu>li>ul {
        display: none;
    }
    
    #menu>li:hover>ul {
        display: block;
    }
</style>
<nav>
    <ul id="menu">
        <li><a href="../clinica">Inicio</a></li>
        <li><a href="../clinica/turno">Turno</a></li>
        <li><a href="../clinica/pedido">Pedido</a></li>
        <li><a href="../clinica/paciente">Paciente</a></li>
    </ul>
</nav>
{% endblock %}

clinica/app_turnos/templates/secretaria/verTurno.html
{% extends "home.html" %} {% block body %}
<style>
    * {
        margin: 0;
        padding: 0;
    }
    
    header {
        font-family: Helvetica;
        width: 480px;
        margin: 0 auto;
    }
    
    ul {
        list-style: none;
    }
    
    #menu li>a {
        background-color: grey;
        color: white;
        padding: 10px;
        display: block;
        text-decoration: none;
        min-width: 100px;
    }
    
    #menu li>a:hover {
        color: #000;
        background-color: #eaeaea;
    }
    
    #menu>li {
        float: left;
        text-align: center
    }
    
    #menu>li>ul {
        display: none;
    }
    
    #menu>li:hover>ul {
        display: block;
    }
</style>
<nav>
    <ul id="menu">
        <li><a href="../clinica">Inicio</a></li>
        <li><a href="../clinica/turno">Turno</a></li>
        <li><a href="../clinica/pedido">Pedido</a></li>
        <li><a href="../clinica/paciente">Paciente</a></li>
    </ul>
</nav>

<input type="search" name="" id="buscador" />
<button value="buscar">
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 16 16"
    class="bi bi-search"
    fill="currentColor"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      fill-rule="evenodd"
      d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"
    />
    <path
      fill-rule="evenodd"
      d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"
    />
  </svg>
  Buscar
</button>

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre del paciente</th>
            <th scope="col">Apellido del paciente</th>
            <th scope="col">Dni</th>
            <th scope="col">Nombre del doctor</th>
            <th scope="col">Apellido del doctor</th>
            <th scope="col">Fecha del turno</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td></td>
            <td></td>
            <td></td>
            <td> </td>
            <td> </td>
            <td> </td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td></td>
            <td></td>
            <td></td>
            <td> </td>
            <td> </td>
            <td> </td>

        </tr>
        <tr>
            <th scope="row">3</th>
            <td></td>
            <td></td>
            <td></td>
            <td> </td>
            <td> </td>
            <td> </td>

        </tr>
    </tbody>
</table>





{% endblock %}

clinica/clinica_APP/templates/gerencia.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
    <link rel="stylesheet" href="../../static/styles/estilo.css" />
    <link
      rel="shortcut icon"
      href="../../static/images/ojo.ico"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="../../static/styles/bootstrap.min.css" />
    
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="rom">
      <h1 id="titulo" class="text-center">Clínica de Optometría</h1>
      <img
        id="logo"
        src="{% static 'images/optometrista.png'%}"
        style="width: 55px"
      />
    </header>

    {% block body %}
    <h1>Plantilla</h1>
    {% endblock%}
    <footer>
      <div>Clínica de Optometría</div>
    </footer>
  </body>
</html>

clinica/clinica_APP/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
    <link rel="stylesheet" href="../../static/styles/estilo.css" />
    <link
      rel="shortcut icon"
      href="../../static/images/ojo.ico"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="../../static/styles/bootstrap.min.css" />

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
      integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <header class="rom">
      <h1 id="titulo" class="text-center">Clínica de Optometría</h1>
      <img
        id="logo"
        src="{% static 'images/optometrista.png'%}"
        style="width: 55px"
      />
    </header>

    {% block body %} {% endblock%}
    <footer>
      <div>Clínica de Optometría</div>
    </footer>
  </body>
</html>

clinica/clinica_APP/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<<<<<<< HEAD
    <title>Clínica de optometría</title>
<<<<<<< HEAD
=======
=======
    <title>Home</title>
>>>>>>> 03a997fba82b3f9193ba5fa73de0379979da9a46
>>>>>>> dec123ef3d46ff38286b2022f579e01b334cc9d3
    <link rel="shortcut icon" href="../../static/images/ojo.ico" type="image/x-icon" />
    <link rel="stylesheet" href="../../static/styles/bootstrap.min.css" />

    <!--<link rel="stylesheet" href="{% static 'styles/estilo.css' %}" /> -->
    <link rel="stylesheet" href="../../static/styles/estilo.css" />
<<<<<<< HEAD

    <style>
        * {
            margin: 0;
            padding: 0;
        }
        
        header {
            font-family: Helvetica;
            width: 480px;
            margin: 0 auto;
        }
        
        ul {
            list-style: none;
        }
        
        #menu li>a {
            background-color: grey;
            color: white;
            padding: 10px;
            display: block;
            text-decoration: none;
            min-width: 100px;
        }
        
        #menu li>a:hover {
            color: #000;
            background-color: #eaeaea;
        }
        
        #menu>li {
            float: left;
            text-align: center
        }
        
        #menu>li>ul {
            display: none;
        }
        
        #menu>li:hover>ul {
            display: block;
        }
    </style>
</head>

<body>

=======
<<<<<<< HEAD

    <style>
        * {
            margin: 0;
            padding: 0;
        }
        
        header {
            font-family: Helvetica;
            width: 480px;
            margin: 0 auto;
        }
        
        ul {
            list-style: none;
        }
        
        #menu li>a {
            background-color: grey;
            color: white;
            padding: 10px;
            display: block;
            text-decoration: none;
            min-width: 100px;
        }
        
        #menu li>a:hover {
            color: #000;
            background-color: #eaeaea;
        }
        
        #menu>li {
            float: left;
            text-align: center
        }
        
        #menu>li>ul {
            display: none;
        }
        
        #menu>li:hover>ul {
            display: block;
        }
    </style>
</head>

<body>

>>>>>>> dec123ef3d46ff38286b2022f579e01b334cc9d3
    <header class="rom">
        <h1 id="titulo" class="text-center">Bienvenido</h1>
        <img id="logo" class="center" src="{% static 'images/optometrista.png'%}" style="width: 55px">
        <nav>
            <ul id="menu">
                <li><a href="../clinica">Inicio</a></li>
                <li><a href="../clinica/turno">Turno</a></li>
                <li><a href="../clinica/pedido">Pedido</a></li>
                <li><a href="../clinica/paciente">Paciente</a></li>
            </ul>
        </nav>
    </header>


    <div class="container w-50 d-flex justify-content-center">
        <form class="form-inline">

            <div class="form-group mb-2">
                <label for="inputSector"></label>
                <select class="custom-select my-1 mr-sm-2" id="inputSector">
              <option selected disabled>Escoja un sector</option>
              <option value="1">Secretaría</option>
              <option value="2">Profesional médico</option>
              <option value="3">Ventas</option>
              <option value="4">Taller</option>
              <option value="5">Gerencia</option>
            </select>
            </div>

            <div class="form-group mx-sm-3 mb-2">
                <label for="inputContraseña" class="sr-only">Contraseña: </label>
                <input type="password" class="form-control" id="inputContraseña" placeholder="Contraseña">
            </div>
<<<<<<< HEAD

            <div class="form-group mx-sm-3 mb-2">
                <button type="submit" class="btn btn-primary">Iniciar</button>
            </div>

        </form>
=======

            <div class="form-group mx-sm-3 mb-2">
                <button type="submit" class="btn btn-primary">Iniciar</button>
            </div>

        </form>
=======
</head>

<body>
    <header class="rom">
        <h1 id="titulo" class="text-center">Bienvenido</h1>
        <img id="logo" src="{% static 'images/optometrista.png'%}" style="width: 55px" />
    </header>
    <div id="inicio" class="row justify-content-center">
        <div class="col-sm-3">
            <label form="menuRol"> Sector : </label>
            <select name="menuRol" id="menuRol">
          <option>Secretaría</option>
          <option>Profesional medico</option>
          <option>Ventas</option>
          <option>Taller</option>
          <option>Gerencia</option>
        </select>
        </div>

        <div class="col-sm-3">
            <form action="#" target="" method="post" name="formDatosPersonales">
                <label>Contraseña:
            <input type="password" name="password" placeholder="contraseña"
          /></label>
            </form>
        </div>
        <button type="button" class="btn btn-primary">Iniciar</button>
>>>>>>> 03a997fba82b3f9193ba5fa73de0379979da9a46
>>>>>>> dec123ef3d46ff38286b2022f579e01b334cc9d3
    </div>

    <footer>
        <div>
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> dec123ef3d46ff38286b2022f579e01b334cc9d3
            Clínica de optometría
        </div>
    </footer>

<<<<<<< HEAD
=======
=======
            Iconos diseñados por
            <a href="https://www.flaticon.es/autores/freepik" title="Freepik">Freepik</a
        >
        from
        <a href="https://www.flaticon.es/" title="Flaticon">www.flaticon.es</a>
        </div>
    </footer>
>>>>>>> 03a997fba82b3f9193ba5fa73de0379979da9a46
>>>>>>> dec123ef3d46ff38286b2022f579e01b334cc9d3
</body>

</html>

clinica/clinica_APP/templates/personalMedico.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
    <link rel="stylesheet" href="../../static/styles/estilo.css" />
    <link
      rel="shortcut icon"
      href="../../static/images/ojo.ico"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="../../static/styles/bootstrap.min.css" />
    
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="rom">
      <h1 id="titulo" class="text-center">Clínica de Optometría</h1>
      <img
        id="logo"
        src="{% static 'images/optometrista.png'%}"
        style="width: 55px"
      />
    </header>

    {% block body %}
    <h1>Plantilla</h1>
    {% endblock%}
    <footer>
      <div>Clínica de Optometría</div>
    </footer>
  </body>
</html>